- app/layout.tsx
- app/preference/page.tsx
- app/styles/globals.ts
- next.config.js
- next.config.mjs
- package.json
- src/lib/registry.tsx
- yarn.lock
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
선호 페이지를 구현했습니다. 
라디오 버튼 및 체크박스를 모두 선택해야 시작하기 버튼이 활성화되는 기능까지 적용했습니다.
이 선택사항이 마이페이지에 반영되는 것은 추후 로그인 기능이 구현된 후 구현해야할 것 같습니다. 
또한 antd 요소에 Pretendard가 적용되도록 코드를 변경했습니다.
--- 
[PC, tablet]
[mobile]
> Feat: 선호 페이지 구현, antd Pretendard 적용

- app/layout.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
각 페이지에서 따로 적용하지 않도록 GlobalStyle을 layout.tsx 내에 import 했습니다.
담당 페이지에서 import하신 GlobalStyle은 삭제해주세요. 
---
> Design: GlobalStyle Layout 반영

- app/layout.tsx
- app/preference/page.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
globalstyle 적용에 맞춰 선호 페이지를 수정했습니다. 
---
> Design: 선호페이지 font-size 수정

- app/styles/typography.ts
- src/components/shared/CustomInput.tsx
- src/components/shared/CustomTextArea.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
- typograpy 변수화
- 공용 Input, Textarea 컴포넌트 UI 완성
--- 
- 로컬 환경 정상 동작
> Feat: typograpy 변수화, 공용 Input, Textarea 컴포넌트 UI 완성

- app/(withHeader)/feeds/page.tsx
- src/components/feeds/FeedPage.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> fix : 피드 데이터 받는 프롭스 추가, 목데이터 내려주는 위치 변경

- src/components/shared/SearchBar.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> Design: 공용 검색바 디자인 수정

- src/components/feeds/FeedPage.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> fix : 타입지정

- app/(withHeader)/mypage/page.tsx
- src/components/mypage/EditProfile.tsx
- src/components/mypage/Profile.tsx
- src/components/shared/Avatar.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
api 나와야 완성 할 수 있을것 같습니다.
---
> feat : 프로필 수정 모달 간이 완성

- src/components/teams/create/CourseRadio.tsx
- src/components/teams/create/MemberCollapse.tsx
- src/components/teams/create/TeamDatePicker.tsx
- src/hooks/teams/create/useTeamCreationForm.ts
- src/types/teams/create/teamCreation.ts
📌 작업 사항
--- 
📌 이슈
--- 
- 기존 모임 생성 시 멤버 나이 설정을 라디오 버튼으로 구현
- 체크박스 버튼으로 변경 필요
📌 작업 내용
--- 
- 체크박스 컴포넌트 적용
- 체크박스로의 변경에 맞게 타입 수정
- 모임 생성 type 파일명 변경(teamsCreate.tsx -> teamCreation.tsx)
--- 
- 로컬 환경 정상 동작
> Feat: 모임 멤버 연령 설정 체크박스 형태로 변경

- src/components/explores/ExplorePage/ExplorePage.tsx
- src/components/shared/AutoSearchBar.tsx
📌 작업 사항
--- 
📌 이슈
--- 
-
📌 작업 내용
--- 
---
> Design: 공용 탭 컴포넌트 적용, Fix: 검색시 리다이렉트 경로 수정

- src/components/review/write/ImgUpload.tsx
- src/components/shared/AutoSearchBar.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
type 프롭 추가하였습니다!!
검색바로 사용하시는 분들은 type="search" 추가해서 사용해주세요!!
ImgUpload 에도 fileList, setFileList 프롭스 추가하였습니다
---
> feat : 자동완성에 타입추가 ( 검색과 장소선택)

- app/(withHeader)/teams/create/page.tsx
- src/components/teams/create/MoutainSearchBar.tsx
- src/lib/axiosInstance.ts
- src/utils/apiUrl.ts
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
- 모임 생성 api 적용
- axios instance 제작
- api url 상수화
--- 
- 로컬 환경에서 정상 동작 확인
> Feat: 모임 생성 api 적용, axios instance 제작 및 api url 상수화

- app/(withHeader)/curation/season/page.tsx
- app/(withHeader)/layout.tsx
- src/components/shared/Footer.tsx
📌 작업 사항
--- 
<br>
📌 작업 내용
--- 
추천페이지 중 하나인 계절별 추천(/curation/season)을 제작했습니다. 
또한 Footer를 제작해 layout.tsx에 추가해뒀습니다. 
산 컴포넌트마다 이미지 크기가 다른 건
탐험 API가 나온 후 오름님이 수정하실 예정이라
컴포넌트 사이의  gap만 잡아뒀습니다.
<br>
---
> Feat: 추천페이지 제작, Footer 제작

- app/(withHeader)/teams/page.tsx
- src/components/shared/TeamThumbnail.tsx
📌 작업 사항
--- 
<br>
📌 작업 내용
--- 
모임페이지에 API를 적용했습니다.
모임 컴포넌트 디자인을 수정하고 연령대를 순서대로 정렬하는 기능을 추가했습니다.
<br>
---
> Feat: 모임페이지 API 연결 및 디자인 수정

- app/(withoutHeader)/preference/page.tsx
📌 작업 사항
--- 
📌 작업 내용
--- 
선호정보 수집 페이지의  value값 수정했습니다.
> Fix: 선호정보 수집 페이지 value값 수정

- src/components/shared/MountainInfo.tsx
📌 작업 사항
--- 
📌 이슈
--- 
- 이미지 크기가 다 제각각이라 width랑 height 값을 고정값으로 주었는데 그러다보니 반응형에 취약한 부분은 감안하고 가야하는지 궁금하네요. 
📌 작업 내용
--- 
---
> Design: 계절 별 산 이미지 크기 고정

- app/(withHeader)/curation/season/page.tsx
- app/(withHeader)/explores/page.tsx
- src/components/explores/KakaoMap.tsx
- src/components/shared/MountainInfo.tsx
- src/types/mountainDataProps.ts
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> Feat: Mountainfo 컴포넌트 type 프롭 추가 Desgin: 계절 추천페이지 산 목록 레이아웃 수정

- app/(withHeader)/teams/[teamId]/page.tsx
- app/(withHeader)/teams/edit/[teamId]/page.tsx
- src/components/teams/create/MoutainSearchBar.tsx
- src/components/teams/userProfile.tsx
- src/types/auth.ts
- src/types/teams/create/teamCreation.ts
- src/types/teams/teamDetails.ts
- src/utils/apiUrl.ts
- src/utils/teams/create/formValidation.ts
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
- 모임 수정 기능 추가
- 모임 참여 기능 개발 중(TODO: 백엔드 측에서 모임 참여 조건 충족 여부 api 완성 후 적용)
---
> Feat: 모임 수정 기능 추가 및 모임 참여 기능 개발 중

- app/(withHeader)/mypage/page.tsx
- src/components/mypage/MyFeeds.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> feat : 저장됨, 내피드 목록 없으면 문구 띄워주기

- app/(withHeader)/mypage/page.tsx
- src/components/mypage/MyFeeds.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> fix : 배열인식오류수정

- app/(withHeader)/page.tsx
- app/(withHeader)/reviews/write/page.tsx
- app/(withHeader)/teams/page.tsx
- app/(withoutHeader)/preference/page.tsx
- src/components/auth/SignIn.tsx
- src/components/main/FeedThumbnail.tsx
- src/components/shared/Header.tsx
- src/components/shared/SearchBar.tsx
- src/lib/axiosInstance.ts
📌 작업 사항
--- 
📌 작업 내용
--- 
1. 메인 @근아 
1. 선호정보 입력 페이지 @근아 
1. 모임페이지 @근아 
---
> Fix/김근아: 메인페이지, 선호정보 입력페이지, 모임페이지 수정

- app/(withHeader)/explores/[exploreId]/details/page.tsx
- app/(withoutHeader)/oauth/kakao/page.tsx
- src/components/shared/MountainInfo.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
- 로그인 로딩 UI 추가했습니다.
--- 
https://github.com/2-6-collaborative-project/Mounteam/assets/105328855/70b3029e-987c-4986-8545-67ffbadb1d31
> fix: 추천 페이지 산 내용 글씨 넘침 수정 Design: 로그인 로딩 스피너 추가

- src/components/shared/TeamThumbnail.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> Fix: 모임컴포넌트 마우스 커서 변경

- app/(withHeader)/feeds/[feedId]/page.tsx
- app/(withHeader)/feeds/page.tsx
- src/components/feeds/Comment.tsx
- src/components/feeds/FeedDetail.tsx
- src/components/feeds/FeedPage.tsx
- src/components/feeds/FeedSearch.tsx
- src/components/feeds/api/FeedData.ts
- src/components/shared/InfoBox.tsx
- src/lib/axiosInstance.ts
- src/types/feeds/FeedData.ts
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> fix: Feature/feed page

- app/(withHeader)/curation/season/page.tsx
📌 작업 사항
--- 
📌 작업 내용
--- 
담당 페이지 중 계절별 추천 페이지에 타입 오류가 있어 수정했습니다.
> Fix: 계절별 추천페이지 타입 오류 수정

- app/(withHeader)/teams/[teamId]/page.tsx
- app/(withHeader)/teams/edit/[teamId]/page.tsx
- src/components/teams/create/MoutainSearchBar.tsx
📌 작업 사항
--- 
📌 이슈
--- 
- 100대 명산 관련 useQuery가 변경됐으나 해당 useQuery를 사용 중이던 mountainSearchBar는 수정되지 않음.
- 이에 따라 mountainSearchBar가 사용된 모임 생성, 모임 수정 페이지에서 에러 발생
📌 작업 내용
--- 
- 변경된 moutain useQuery에 맞춰 사용 중이던 mountainSearchBar컴포넌트 수정
- 모임 신청 Modal에 Pretendard 폰트 적용
--- 
- 로컬 환경 정상 동작 확인
> Fix: moutainSearchBar 관련 에러 해결 및 모임 신청 Modal font 적용

- app/(withHeader)/explores/page.tsx
- src/components/explores/api/getMountainList.ts
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
- 무한스크롤 구현했습니다.
--- 
https://github.com/2-6-collaborative-project/Mounteam/assets/105328855/60b86ff6-feb7-412a-b5ed-6c0f2c677b67
> Feat: 탐험 페이지 무한스크롤 구현

- app/(withHeader)/layout.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> Fix: queryProvider 문자 수정

- src/components/feeds/FeedPage.tsx
- src/components/feeds/FeedSearch.tsx
- src/components/shared/InfoBox.tsx
- src/components/shared/SearchBar.tsx
- src/lib/axiosInstance.ts
- src/types/feeds/FeedData.ts
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
---  타입에러 해결 및 피드페이지 필터기능 미작동 작동되게 수정완료
---
> Feat: 타입에러 해결 및 피드페이지 필터기능 미작동 작동되게 수정완료

- app/(withHeader)/explores/page.tsx
- next.config.js
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> fix: 배포 이슈

- app/(withHeader)/certification/page.tsx
- app/(withHeader)/curation/season/page.tsx
- app/(withHeader)/explores/page.tsx
- app/(withHeader)/feeds/page.tsx
- app/(withHeader)/layout.tsx
- app/(withHeader)/mypage/page.tsx
- app/(withHeader)/page.tsx
- app/(withHeader)/teams/create/page.tsx
- app/(withHeader)/teams/page.tsx
- app/(withHeader)/teams/write/page.tsx
- src/components/auth/SignIn.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
- 카카오 리다이렉트 URI 배포된 주소로 변경했습니다.
---
> Fix: 카카오 로그인 리다이렉트 URI 변경

- src/components/auth/SignIn.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> fix: 카카오 로그인 리다이렉트 uri 수정

- src/utils/apiUrl.ts
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> Fix: api 베이스 주소 변경

- app/(withHeader)/mypage/page.tsx
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
엑세스 토큰이 없을 시 (로그인 X) 페이지 로드가 안되게 했습니다
원래 하려던 작업이 토큰이 없으면 로그인 페이지로 가게 하는 것이였는데 레이아웃에 토큰이 없으면 alert 창뜨면서
로그인 페이지로 가는 기능이 있어서 로드만 안되게 바꿨습니다!
---
> feat : 엑세스 토크 없을시 페이지 로드 안되게 설정

- app/(withHeader)/mypage/page.tsx
- app/(withHeader)/page.tsx
- src/components/main/FeedThumbnail.tsx
📌 작업 사항
--- 
<br>
📌 작업 내용
--- 
메인페이지 내 피드 컴포넌트의 경로를 수정하고 반응형을 수정했습니다.
<br>
---
> Chore: 피드 썸네일 컴포넌트 수정

- app/(withHeader)/curation/season/page.tsx
- public/leftbutton.svg
- public/rightbutton.svg
📌 작업 사항
--- 
📌 작업 내용
--- 
계절별 추천페이지 내 산들을 넘겨볼 수 있는 버튼을 추가했습니다. 
--- 
https://github.com/2-6-collaborative-project/Mounteam/assets/148167964/7331c8e3-1760-421e-a42f-6f6196077443
> Feat: 계절별 추천 페이지 버튼 기능 추가

- app/(withHeader)/mypage/page.tsx
- src/components/mypage/EditProfile.tsx
- src/components/mypage/api/deleteMyTeam.ts
- src/components/mypage/api/getMyFeedData.ts
- src/components/mypage/api/getMyTeamsData.ts
- src/components/mypage/api/getUserData.ts
- src/components/mypage/api/postUserData.ts
- src/components/review/write/api/postRevieWrite.ts
- src/components/teams/write/api/getTeamsData.ts
- src/components/teams/write/api/postTeamsReview.ts
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
api 줏 변경되고 나서 건들지 않아서 변경하였습니다
---
> fix : api 주소 수정

- app/(withHeader)/teams/page.tsx
- src/components/shared/TeamThumbnail.tsx
- src/components/teams/DateFilter.tsx
- src/components/teams/GenderFilter.tsx
- src/components/teams/TeamFilterPanel.tsx
📌 작업 사항
--- 
📌 작업 내용
--- 
서버비용으로 인해 추가 개발을 멈춰야할 것 같아 무한 스크롤 구현을 중지하고 PR을 올립니다. 
모임 페이지의 디자인 구현을 완료했습니다.
---
> design: 모임페이지 디자인 구현

- README.md
📌 작업 사항
--- 
📌 이슈
--- 
📌 작업 내용
--- 
---
> 계절별, 메인페이지 동영상 수정
